[package]
name = "seeai-object-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
object_store.workspace = true
seeai-application = { path = "../application" }

[lints]
workspace = true
