[package]
name = "seeai-alert-webhook"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
reqwest.workspace = true
seeai-application = { path = "../application" }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
chrono.workspace = true
seeai-domain = { path = "../domain" }
